x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  networks:
    - airflow-net
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    _PIP_ADDITIONAL_REQUIREMENTS: boto3 pandas
    AIRFLOW_UID: ${AIRFLOW_UID:-50000}
    AIRFLOW_CONN_DW_CONN: postgresql://etl_user:etl_password@data_warehouse:5432/analytics_db
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    # --- CREDENCIALES AWS PARA BOTO3 ---
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-eu-west-1}
    AWS_ENDPOINT_URL: "http://localstack:4566"
    # Conexión nativa de Airflow para AWS apuntando a LocalStack
    AIRFLOW_CONN_AWS_DEFAULT: "aws://?region_name=eu-west-1&endpoint_url=http%3A%2F%2Flocalstack%3A4566"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  depends_on:
    postgres:
      condition: service_healthy
    localstack:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    networks:
      - airflow-net
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  data_warehouse:
    image: postgres:13
    networks:
      - airflow-net
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "etl_user", "-d", "analytics_db"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  prometheus:
    image: prom/prometheus:v3.14.0
    networks:
      - airflow-net
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    networks:
      - airflow-net
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro
    command:
      - -containerd=/run/containerd/containerd.sock
      - -containerd-namespace=moby
    ports:
      - "8081:8080"

  pushgateway:
    image: prom/pushgateway:v1.11.3
    container_name: pushgateway
    networks:
      - airflow-net
    ports:
      - "9091:9091"

  localstack:
    image: localstack/localstack:3.8.0 # Fijamos una versión estable comunitaria
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      # - SERVICES=kinesis  <-- ELIMINAR O COMENTAR ESTA LÍNEA
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
    volumes:
      - ./localstack-init/init_kinesis.sh:/etc/localstack/init/ready.d/init_kinesis.sh
    networks:
      airflow-net:
        aliases:
          - localstack
          - aws.localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  emitter:
    image: python:3.13-slim
    container_name: kinesis_emitter
    networks:
      - airflow-net
    volumes:
      - ./emitter:/app
    working_dir: /app
    # Instalamos las dependencias al vuelo y ejecutamos el script
    command: bash -c "pip install boto3 && python emitter.py"
    environment:
      - KINESIS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
    depends_on:
      localstack:
        condition: service_healthy
      pushgateway:
        condition: service_started

networks:
  airflow-net:
    driver: bridge